config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :arcade, :xo, :coinflip, :users

  resources :matches do
    get :place_piece
  end

  post 'users/:id' => 'users#update'

  root to: 'arcade#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role? :admin
      can :manage, :all
        elsif user.role? :user
      can :read, :all
    end
  end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/arcade.rb
class Arcade < ActiveRecord::Base
  has_many :matches
  has_one :xo  
  has_one :coinflip

  def games
    [xo, coinflip]
  end
end

app/models/coinflip.rb
class Coinflip < ActiveRecord::Base
  belongs_to :arcade
end

app/models/match.rb
class Match < ActiveRecord::Base
  has_one :user, foreign_key: "user_1_id", class_name: "User"
  has_one :other_user, foreign_key: "user_2_id", class_name: "User"
  has_many :moves
  belongs_to :arcade

  def player_finder(user)
    User.find(self.user)
  end


end

app/models/move.rb
class Move < ActiveRecord::Base
  belongs_to :match
  enum piece: [:o, :x]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_many :matches

  before_save :default_values

  # def initialize
  #   @image = :image
  # end

  def default_values
    self.image ||= 'default_av.gif'
  end

  def user_image
    @image
  end

  def win_record
  wins = Match.where(winner: self.id).count
  percentage = wins.fdiv(Match.all.count) * 100
  end


end

app/models/xo.rb
require 'xogamestate'

class Xo < ActiveRecord::Base
  belongs_to :arcade
  has_many :matches, through: :arcade
end

app/models/xo_game_state.rb
class XoGameState
  attr_accessor :board, :pieces, :turn, :match

  def initialize(match)
    @match = match
    @board = [
      [nil,nil,nil],
      [nil,nil,nil],
      [nil,nil,nil] 
    ]
    @pieces = [:o, :x]
  end

  def show_board
    @board
  end

  def next_piece
    @pieces[ number_of_turns % 2 ]
  end

  def last_piece
    @pieces[ (number_of_turns + 1) % 2 ]
  end

  def drawn?
    number_of_turns == 9
  end

  def create_move(row, column)
    @match.moves.create(row: row, column: column, piece: next_piece)
    refresh_board()
    if has_won?(last_piece.to_s)
      declare_result('win')
    elsif drawn?
      declare_result('draw')
    end
  end 

  def refresh_board
    moves = @match.moves
    moves.each do |move|
      @board[move.row][move.column] = move.piece if move.row && move.column
    end
  end

  def number_of_turns
    @match.moves.count
  end

  def has_won?(symbol)
    if horizontal_line?(symbol, @board) ||
    vertical_line?(symbol) ||
    diagonal_line?(symbol)
      return true
    end
  end

  def horizontal_line?(symbol, board)
    board.any? do |row|
      row_has_winning_line(row, symbol)
    end
  end

  def vertical_line?(symbol)
    transp_board = @board.transpose
    horizontal_line?(symbol, transp_board)
  end

  def diagonal_line?(symbol)
    middle_piece = @board[1][1]
    return false if middle_piece != symbol
    topleft_bottomright = @board[0][0] == symbol && @board[2][2] == symbol
    bottomleft_topright = @board[2][0] == symbol && @board[0][2] == symbol
    topleft_bottomright || bottomleft_topright
  end

  def row_has_winning_line(row, symbol)
    row.all? do |square|
    square == symbol
    end
  end



  def declare_result(result)
    #updates @match.winner to reflect result (0 for draw), redirect to custom_route?
    if result == 'draw'
      @match.winner = 0
    else
      if number_of_turns.odd?
        @match.winner = @match.user_1_id
      else
        @match.winner = @match.user_2_id
      end
    end

    @match.game_state = "completed"
    @match.save
  end

end

app/models/xogamestate.rb
class XoGameState
  attr_accessor :board, :pieces, :turn

  def initialize(match)
    @board = [
      [nil,nil,nil],
      [nil,nil,nil],
      [nil,nil,nil] 
    ]
    @pieces = [:o, :x]
    @turn = 0
    match.moves.each
  end

  def turn_count
    @turn += 1
  end

  def show_board
    @board
  end

  def update_board (row, column)
    @board[row][column] = @pieces[ @turn % 2 ]
    redirect_to xo_path
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/arcade_controller.rb
class ArcadeController < ApplicationController

  def index
  end

end

app/controllers/coinflip_controller.rb
class CoinflipController < ApplicationController
  
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def show
    @match = Match.find(params[:id])
    @game_state = XoGameState.new(@match)
    @game_state.refresh_board
  end

  def index
    @matches = Match.all
  end

  def place_piece
    @match = Match.find(params[:match_id])  
    @game_state = XoGameState.new(@match)
    @game_state.create_move(params[:row], params[:column])
    redirect_to match_path(@match)
  end

  def create
    @match = Match.create(match_params)
    what_type = params[:game]
    if what_type == "xo"
      @match.game_type = "xo"
    elsif what_type == "coinflip"
      @match.game_type = "coinflip"
    end
    @match.game_state = "playing"
    @match.save
    redirect_to match_path(@match.id)
  end

  private

  def match_params
    params.require(:match).permit(:user_1_id, :user_2_id, :game_type, :arcade_id, :result, :game_state)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # before_action :load_user, except: [:index, :create, :new]


    def index
      @users = User.all
    end

    def show

    end

    def new
      @user = User.new
    end

    def edit
    end

    def create
     @user = User.new(user_params)
     @user.save
     redirect_to user_path
    end

    def update
        @user = User.find(current_user)
        @user.update_attributes(user_params)
        redirect_to user_path
    end

    def destroy

    end

    



    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :content, :user_id, :article_id, :image)
    end

  
end

app/controllers/xo_controller.rb
class XoController < ApplicationController



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arcade_helper.rb
module ArcadeHelper
end

app/helpers/coinflip_helper.rb
module CoinflipHelper
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/xo_helper.rb
module XoHelper
end

app/views/arcade/index.html.erb
<center>
<br><br>
<%= link_to image_tag("blank.png"), new_match_path  %>
<br>
<b>Play noughts and crosses</b>
</center>

app/views/matches/index.html.erb
<% @matches.each do |match| %>
<%= match.user_1_id %>
<%= match.user_2_id %>
<% end %>

app/views/matches/new.html.erb
<center>
  <% challenge = Match.new %>
  <%= form_for challenge do |f| %>
  <%= f.hidden_field :arcade_id, value: Arcade.first.id  %>
  <%= f.hidden_field :user_1_id, value: current_user.id %>
  <%= f.collection_select :user_2_id, User.order(:name), :id, :name %>
  <%= radio_button_tag(:game, "xo") %>
  <%= label_tag(:game_1_id, "Play XO") %>
  <%= radio_button_tag(:game, "coinflip") %>
  <%= label_tag(:game_2_id, "Play Coinflip") %>
  <br><br>
  <%= f.submit 'Send challenge!' %>
  <% end %>

</center>

app/views/matches/show.html.erb
<center>
<% if @match.game_state == 'completed' %>
  <% if  @match.winner == 0 %>
    The game is drawn
  <% else %>
    The Winner IS..  <%= User.find(@match.winner).name %>
  <% end %>
<% else %>
  <p><b>How to play:</b></p>
  <p>Click on a space to place your piece there</p>
<% end %>


  <table>
    <tbody>
      <% @game_state.show_board.each_with_index do |row, row_index| %>
      <tr>
        <% row.each_with_index do |place, column_index| %>
        <td><% if place.nil? %>
              <% if @match.game_state == 'completed' %>
                <%= image_tag("blank.png") %>
              <% else %>
                <%= link_to(image_tag("blank.png"), match_place_piece_path(@match, {row: row_index, column: column_index}))%>
              <% end %>
          <% elsif place == "x" %>
          <%= image_tag("x.png") %>
          <% elsif place == "o" %>
          <%= image_tag("o.png") %>
          <% end %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </center>

app/views/users/show.html.erb
<center>

  <br><br>

  <b>Name:</b>
  <%= current_user.name %>
  <br><br>
  <b>Avatar:</b><br>
  <%= image_tag current_user.image, style: 'height:100px;width:auto;' %>
  <%= form_for current_user do |f| %>
  <b><%= f.label 'Change avatar' %></b>
  <br>
  <%= f.text_field :image %>
  <br>
  <%= f.submit 'Update avatar'%>
  <br>
  <% end %>
  <br><br>
  <b>Win record:</b>
  <br>

  <%= current_user.win_record %>%
  

  <br><br><br>

  <main class ="container">
      <section class = "row">
        <div class = "grid grid-3">
          <div class = "panel panel-primary">
            <div class = "panel-heading">Opponent</div>
            <div class = "panel-body">
              <% Match.all.each do |match| %>
                <% if match.user_1_id == current_user.id %>
                  <% opponent = match.user_2_id %>
                <% else %>
                  <% opponent = match.user_1_id %>
                <% end %>
                  <%= User.find(opponent).name %>
                <br><br>
              <% end %>
            </div>
          </div>
        </div>

        <div class = "grid grid-3">
          <div class = "panel panel-primary">
            <div class = "panel-heading">Played</div>
            <div class = "panel-body">
              <% Match.all.each do |match| %>
                <%= match.updated_at %>
                <br>
              <% end %>
            </div>
          </div>
        </div>

        <div class = "grid grid-3">
          <div class = "panel panel-primary">
            <div class = "panel-heading">Result</div>
            <div class = "panel-body">
              <% Match.all.each do |match| %>
                <% if match.winner == current_user.id %>
                  <%= "win" %>
                  <br><br>
                <% elsif match.winner == 0 %>
                  <%= "draw" %>
                  <br><br>
                <% elsif match.winner != current_user.id %>
                  <%= "loss" %>
                  <br><br>
                <% end %> 
              <% end %>
            </div>
          </div>
        </div>
      </section>
    </main>


</center>